#!/bin/fish
#
# diffmk - Update ports that get listed by diffls
# onodera, https://github.com/onodera-punpun

## EXECUTE

# Load library
source /usr/include/prtstuff

getopts $argv | while read -l opt val
	switch $opt
		case h help
			echo -e 'Usage: diffmk [options]\n'
			echo 'options:'
			echo '  -r,   --readme          toggle opening of readmes'
			echo '  -s,   --script          toggle execution of pre- and post-install'
			echo '  -h,   --help            print help and exit'
			exit 0
		case r readme
			if test $readme = true
				set readme false
			else
				set readme true
			end
		case s script
			if test $script = true
				set script false
			else
				set script true
			end
		case '*'
			echo 'Invalid option, use -h for help.' >/dev/stderr
			exit 1
	end
end

prtonlyroot 'update ports'
prtinstall (diffls)
