#!/bin/fish
#
# lsdiff - List installed ports with a different version available in the ports tree
# onodera, https://github.com/onodera-punpun

## EXECUTE

# Load library
source /usr/include/prtstuff

# Initialize default option values
set oldnew false

getopts $argv | while read -l opt val
	switch $opt
		case h help
			echo -e 'Usage: lsdiff [options]\n'
			echo 'options:'
			echo '  -v,   --version         list installed and available version'
			echo '  -h,   --help            print help and exit'
			exit 0
		case v version
			set oldnew true
	end
end

# Get installed ports
set installed (lsprt -i)

# Get versions and locations
set names (string replace -r ' .*' '' $installed)
set versions (string replace -r '.* ' '' $installed)
set locations (locprt $names)

for count in (seq (count $locations))
	set version $versions[$count]
	set available (prtpkgfile $locations[$count] | string match -r '^version=.*|^release=.*' | string replace -r '^version=|^release=' '' | string join '-')

	if test $version != $available
		if test $oldnew = true
			echo "$locations[$count] $version$dark -> $foreground$available"
		else
			echo $locations[$count]
		end
	end
end
