#!/bin/fish
#
# mkdiff - Update ports that get listed by lsdiff
# onodera, https://github.com/onodera-punpun

## EXECUTE

# Load library
source /usr/include/prtstuff

# Initialize default option values
set verbose false

getopts $argv | while read -l opt val
	switch $opt
		case h help
			echo -e 'Usage: mkdiff [options]\n'
			echo 'options:'
			echo '  -s,   --script          toggle execution of pre- and post-install'
			echo '  -v,   --verbose         enable verbose output'
			echo '  -h,   --help            print help and exit'
			exit 0
		case s script
			if test $script = true
				set script false
			else
				set script true
			end
		case v verbose
			set verbose true
		case '*'
			echo 'Invalid option, use -h for help.' >/dev/stderr
			exit 1
	end
end

set method update
prtonlyroot "$method ports"
prtinstall (lsdiff)
