#!/bin/fish
#
# provprt - Search ports for files they provide
# onodera, https://github.com/onodera-punpun

## EXECUTE

# Load library
source /usr/include/prtstuff

if test (count $argv) -ge 1
	getopts $argv | while read -l opt val
		switch $opt
			case h help
				echo -e 'Usage: provprt [options] [queries]\n'
				echo 'options:'
				echo '  -h,   --help            print help and exit'
				exit 0
			case '*'
				set results (find $portdir -type f -name .footprint | xargs grep -i $val)

				for line in $results
					set port (echo $line | cut -d \t -f 1 | cut -d '.' -f 1 | string replace $portdir '' | string trim -c '/')

					if test $val != $port
						set val $port
						if test $status -ge 1
							exit 1
						end

						echo $val
					end

					echo (echo $line | cut -d \t -f 3 | sed "s/^/$dark-> $foreground\//g")
				end
		end
	end
else
	echo 'Please specify a query.' >/dev/stderr
	exit 1
end
