#!/bin/fish
#
# prtdiff - List the difference between installed ports and ports in your repos
# onodera, https://github.com/onodera-punpun

## EXECUTE

# Load library
source /usr/include/prtstuff

if test (count $argv) -eq 1
	switch $argv
		case -h --help
			echo -e 'Usage: prtdiff [options]\n'
			echo 'options:'
			echo '  -h,   --help            print help and exit'
			exit 0
		case '*'
			echo 'Invalid option, use -h for help.' >/dev/stderr
			exit 1
	end
end

# Get all and installed ports
set ports (prtls)
set installed (prtls -i | cut -d ' ' -f 1)
set installedver (prtls -i | cut -d ' ' -f 2)

prtloc $installed
