#!/bin/fish
#
# prtdiff - List the difference between installed ports and ports in your repos
# onodera, https://github.com/onodera-punpun

## EXECUTE

# Load library
source /usr/include/prtstuff

if test (count $argv) -eq 1
	switch $argv
		case -h --help
			echo -e 'Usage: prtdiff [options]\n'
			echo 'options:'
			echo '  -h,   --help            print help and exit'
			exit 0
		case '*'
			echo 'Invalid option, use -h for help.' >/dev/stderr
			exit 1
	end
end

# Get installed ports
set installed (prtls -i)

for port in $installed
	set name (echo $port | cut -d ' ' -f 1)

	set availversion (prtpkgfile (prtloc $name))
	set instversion (echo $port | cut -d ' ' -f 2)

	echo $name
	echo $instversion $availverion
end
