#!/bin/fish
#
# prtdiff - List the difference between installed ports and ports in your repos
# onodera, https://github.com/onodera-punpun

# TODO: Fucks up if there are ports installed that are not in portdir

## EXECUTE

# Load library
source /usr/include/prtstuff

getopts $argv | while read -l opt val
	switch $opt
		case h help
			echo -e 'Usage: prtdiff [options]\n'
			echo 'options:'
			echo '  -h,   --help            print help and exit'
			exit 0
		case '*'
			echo 'Invalid option, use -h for help.' >/dev/stderr
			exit 1
	end
end

# Get installed ports
set installed (prtls -i)
set locations (prtloc (echo $installed | string split ' '))

for port in (seq (count $installed))
	set availversion (prtpkgfile $location[$count] | string match -r '^version=.*|^release=.*' | string replace -r '^version=|^release=' '' | string join '-')
	set instversion (echo $installed[$count] | cut -d ' ' -f 2)

	if test $availversion != $instversion
		echo (echo $installed[$count] | cut -d ' ' -f 1)
	end
end
