#!/bin/fish
#
# prtl - Prints port location
# onodera, https://github.com/onodera-punpun

## EXECUTE

# Load library
source /usr/include/prtstuff

if test (count $argv) -ge 1
	switch "$argv"
		case -h --help
			echo -e 'Usage: prtloc [options] [ports]\n'
			echo 'options:'
			echo '  -h,   --help            print help and exit'
			exit 0
		case '*'
			# Get all ports
			set ports (prtls)

			prtlocation $argv
	end
else
	echo 'Please specify a port.' >/dev/stderr
	exit 1
end
