#!/bin/fish
#
# prtprovide - Search ports for files they provide
# onodera, https://github.com/onodera-punpun

# TODO: -> /usr/lib/libconfig++.so -> /-> -> /libconfig++.so.9.2.0
# TODO:-> /usr/lib/libconfig++.so.9 -> /-> -> /libconfig++.so.9.2.0

## EXECUTE

# Load library
source /usr/include/prtstuff

if test (count $argv) -ge 1
	getopts $argv | while read -l opt val
		switch $opt
			case h help
				echo -e 'Usage: prtprovide [options] [queries]\n'
				echo 'options:'
				echo '  -h,   --help            print help and exit'
				exit 0
			case '*'
				set results (find $portdir -type f -name .footprint | xargs grep -i $val)

				for line in $results
					if test $val != (echo $line | cut -d \t -f 1 | cut -d '.' -f 1 | string replace $portdir '' | string trim -c '/')
						set val (echo $line | cut -d \t -f 1 | cut -d '.' -f 1 | string replace $portdir '' | string trim -c '/')
						if test $status -ge 1
							exit 1
						end

						echo $val
					end

					echo (echo $line | cut -d \t -f 3 | tr ' ' '\n' | sed "s/^/$dark-> $foreground\//g")
				end
		end
	end
else
	echo 'Please specify a query.' >/dev/stderr
	exit 1
end
