#!/bin/fish
#
# prtpatch - Patches ports
# onodera, https://github.com/onodera-punpun

## EXECUTE

# Load library
source /usr/include/prtstuff

if test (count $argv) -ge 1
	switch "$argv"
		case -h --help
			echo -e 'Usage: prtpatch [ports]\n'
			echo 'options:'
			echo '  -h,   --help            print help and exit'
			exit 0
		case '*'
			echo 'Invalid option, use -h for help.' >/dev/stderr
			exit 1
	end
end

prtonlyroot 'patch ports'

# Set patches
set patches (find "$patchdir/" -type f -name '*.patch')

for patch in $patches
	set repo (echo $patch | rev | cut -d '/' -f 3 | rev)
	set port (echo $patch | rev | cut -d '/' -f 2 | rev)
	set file (echo $patch | rev | cut -d '/' -f 1 | rev | cut -d '.' -f 1)

	echo "patching $bright$repo/$port/$file$foreground."
	patch -N "$portdir/$repo/$port/$file" -i $patch >/dev/null
	if test $status -ge 1
		echo "Patching $bright$repo/$port/$file$foreground failed." >/dev/stderr
		exit 1
	end
end
