#!/bin/fish
#
# prtprovide - Search ports for files they provide
# onodera, https://github.com/onodera-punpun

# TODO: -> /usr/lib/libconfig++.so -> /-> -> /libconfig++.so.9.2.0
# TODO:-> /usr/lib/libconfig++.so.9 -> /-> -> /libconfig++.so.9.2.0

## CONFIGURATION

# Set config dir location
set configdir /etc/prtstuff


## EXECUTE

# Load config
source $configdir/config

if test (count $argv) -ge 1
	for flag in $argv
		switch $flag
			case -h --help
				echo -e 'Usage: prtprovide [query]\n'
				echo 'options:'
				echo '  -h,   --help            print help and exit'
				exit 0
			case '*'
				set results (find $portdir -type f -name .footprint | xargs grep -i $argv)

				for line in $results
					if test "$port" != (echo $line | cut -d \t -f 1 | cut -d '.' -f 1 | string replace $portdir '' | string trim -c '/')
						set port (echo $line | cut -d \t -f 1 | cut -d '.' -f 1 | string replace $portdir '' | string trim -c '/')
						echo $port
					end

					echo (echo $line | cut -d \t -f 3 | tr ' ' '\n' | sed 's/^/'(set_color black --bold)'-> '(set_color normal)'\//g')
				end
		end
	end
else
	echo 'Please specify a query.' >/dev/stderr
	exit 1
end
