# Location of the ports tree and pkgutil directories.
prtdir = "/usr/src/prt"
pkgdir = "/usr/src/pkg/pkg"
srcdir = "/usr/src/pkg/src"
wrkdir = "/usr/src/pkg/wrk"

# Repo order, the port found first is used.
order = [
	"core",
	"opt",
	"xorg",
	"contrib"
]

# Alias ports.
aliases = [
#	[ { repo = "core",        port = "openssl" },
#	  { repo = "6c37-dropin", port = "libressl" } ],

#	[ { repo = "core",        port = "pkg-config" },
#	  { repo = "6c37-dropin", port = "pkgconf" } ],
]

# Characters used for indentation.
indentchar = "-  "

# Characters used for warnings.
warningchar = "!  "

# Color used for indentation, arrows, et cetera.
# See: https://misc.flogisoft.com/bash/tip_colors_and_formatting
darkcolor = 90

# Color used to highlight repos to pull, ports to install, et cetera.
lightcolor = 93

# Color used for warnings.
warningcolor = 91

# Repos to pull.
[repo]
	[repo.contrib]
	url = "git://crux.nu/ports/contrib"
	branch = "3.2"

	[repo.core]
	url = "git://crux.nu/ports/core"
	branch = "3.2"

	[repo.opt]
	url = "git://crux.nu/ports/opt"
	branch = "3.2"

	[repo.xorg]
	url = "git://crux.nu/ports/xorg"
	branch = "3.2"
