# Location of the ports tree.
portdir = "/usr/ports"

# Repo order, the port found first is used.
order = [
	"core",
	"opt",
	"xorg",
	"contrib"
]

# Alias ports.
alias = [
#	[ "core/openssl", "6c37-dropin/libressl" ],
#	[ "core/pkg-config", "6c37-dropin/pkgconf" ],
#	[ "opt/cairo", "6c37-dropin/cairo-iu" ],
#	[ "opt/fontconfig", "6c37-dropin/fontconfig-iu" ],
#	[ "opt/freetype", "6c37-dropin/freetype-iu" ]
]

# Characters used for indentation.
indentchar = "-  "

# Characters used for errors.
errorchar = "!  "

# Color used for indentation, arrows, et cetera.
darkcolor = 8

# Color used for errors.
errorcolor = 9

# Color used to highlight repos to pull, ports to install, et cetera.
lightcolor = 11

# Repos to pull.
[pull]
	[pull.contrib]
	url = "git://crux.nu/ports/contrib"
	branch = "3.2"

	[pull.core]
	url = "git://crux.nu/ports/core"
	branch = "3.2"

	[pull.opt]
	url = "git://crux.nu/ports/opt"
	branch = "3.2"

	[pull.xorg]
	url = "git://crux.nu/ports/xorg"
	branch = "3.2"
