#!/bin/fish
#
# build - Build and install ports
# onodera, https://github.com/onodera-punpun

# TODO: Fix 3/3 for 3/4 (deps + pwd)

## EXECUTE

# Load util
source /usr/share/prt/util

# Initialize default option values
set verbose false

getopts $argv | while read -l opt val
	switch $opt
		case h help
			echo -e 'Usage: prt build [arguments]\n'
			echo 'arguments:'
			echo '  -s,   --script          toggle execution of pre- and post-install'
			echo '  -v,   --verbose         enable verbose output'
			echo '  -h,   --help            print help and exit'
			exit 0
		case s script
			if test $script = true
				set script false
			else
				set script true
			end
		case v verbose
			set verbose true
		case '*'
			echo 'Invalid argument, use -h for a list of arguments.' >/dev/stderr
			exit 1
	end
end

if string match -q -r (prtpkgfile | string match -r '^name=.*' | cut -d '=' -f 2) (prt list -i)
	set methodi update
else
	set methodi install
end
prtonlyroot "$methodi ports"

set depends (prt depends | tac)
if test (count $depends) -ge 1
	set method install
	prtinstall (prt depends | tac)
end

set method $methodi
prtinstall
