#!/bin/fish
#
# diff - List outdated packages
# onodera, https://github.com/onodera-punpun

## EXECUTE

# Load util
source /usr/share/prt/util

# Initialize default option values
set version false

getopts $argv | while read -l opt val
	switch $opt
		case h help
			echo -e 'Usage: prt diff [arguments]\n'
			echo 'arguments:'
			echo '  -v,   --version         list installed and available version'
			echo '  -h,   --help            print help and exit'
			exit 0
		case v version
			set version true
	end
end

set installed (prt list -i -v)

set names (echo $installed | cut -d ' ' -f 1)
set versions (echo $installed | cut -d ' ' -f 2)
set locations (prt location $names)

for count in (seq (count $locations))
	set version $versions[$count]
	set available (prtpkgfile $locations[$count] | string match -r '^version=.*|^release=.*' | cut -d '=' -f 2 | cut -d ' ' -f 1 | string join '-')

	if test $version != $available
		if test $version = true
			if isatty stdout
				echo "$locations[$count] $version$dark -> $foreground$available"
			else
				echo "$locations[$count] $version -> $available"
			end
		else
			echo $locations[$count]
		end
	end
end
