#!/bin/fish
#
# info - Prints port information
# onodera, https://github.com/onodera-punpun

## EXECUTE

# Load util
source /usr/share/prt/util

if test (count $argv) -ge 1
	getopts $argv | while read -l opt val
		switch $opt
			case h help
				echo -e 'Usage: prt info [arguments]\n'
				echo 'arguments:'
				echo '  -d,   --description     print description'
				echo '  -u,   --url             print url'
				echo '  -m,   --maintainer      print maintainer'
				echo '  -e,   --dependencies    print dependencies'
				echo '  -o,   --optional        print optional dependencies'
				echo '  -v,   --version         print version'
				echo '  -r,   --release         print release'
				echo '  -h,   --help            print help and exit'
				exit 0
			case d description
				echo 'Description: '(prtpkgfile | string match -r '^# Description:.*' | cut -d ':' -f 2- | string trim)
			case u url
				echo 'URL: '(prtpkgfile | string match -r '^# URL:.*' | cut -d ':' -f 2- | string trim)
			case m maintainer
				echo 'Maintainer: '(prtpkgfile | string match -r '^# Maintainer:.*' | cut -d ':' -f 2- | string trim)
			case e dependencies
				echo 'Depends on: '(prtpkgfile | string match -r '^# Depends on:.*' | cut -d ':' -f 2- | string replace -a ',' '' | string trim)
			case o optional
				# TODO: Remove the OR once 6c37 is fixed
				echo 'Nice to have: '(prtpkgfile | string match -r '^# (Optional|Nice to have):.*' | head -n 1 | cut -d ':' -f 2- | string replace -a ',' '' | string trim)
			case r release
				echo 'Release: '(prtpkgfile | string match -r '^release=.*' | cut -d '=' -f 2-)
			case v version
				echo 'Version: '(prtpkgfile | string match -r '^version=.*' | cut -d '=' -f 2-)
			case r release
				echo 'Release: '(prtpkgfile | string match -r '^release=.*' | cut -d '=' -f 2-)
			case '*'
				echo 'Invalid arguments, use -h for a list of arguments.' >/dev/stderr
				exit 1
		end
	end
else
	# TODO: I could optimize by not using prtpkgfile each time?
	echo 'Description: '(prtpkgfile | string match -r '^# Description:.*' | cut -d ':' -f 2- | string trim)
	echo 'URL: '(prtpkgfile | string match -r '^# URL:.*' | cut -d ':' -f 2- | string trim)
	echo 'Maintainer: '(prtpkgfile | string match -r '^# Maintainer:.*' | cut -d ':' -f 2- | string trim)
	echo 'Depends on: '(prtpkgfile | string match -r '^# Depends on:.*' | cut -d ':' -f 2- | string replace -a ',' '' | string trim)
	# TODO: Remove the OR once 6c37 is fixed
	echo 'Nice to have: '(prtpkgfile | string match -r '^# (Optional|Nice to have):.*' | head -n 1 | cut -d ':' -f 2- | string replace -a ',' '' | string trim)
	echo 'Version: '(prtpkgfile | string match -r '^version=.*' | cut -d '=' -f 2-)
	echo 'Release: '(prtpkgfile | string match -r '^release=.*' | cut -d '=' -f 2-)
end
