#!/bin/fish
#
# list - List repos and ports
# onodera, https://github.com/onodera-punpun

## EXECUTE

# Load util
source /usr/share/prt/util

if test (count $argv) -ge 1
	getopts $argv | while read -l opt val
		switch $opt
			case h help
				echo -e 'Usage: prt list [arguments]\n'
				echo 'arguments:'
				echo '  -i,   --installed       list installed ports'
				echo '  -r,   --repos           list repos'
				echo '  -h,   --help            print help and exit'
				exit 0
			case i installed
				grep -A 2 '^$' /var/lib/pkg/db | 'tr' \n ' ' | string replace -r -a '\-\-' '\n' | string trim | head -n -1
				exit 0
			case r repos
				find $prtdir -mindepth 1 -maxdepth 1 -type d | string replace "$prtdir/" '' | sort
				exit 0
			case '*'
				echo 'Invalid argument, use -h for a list of arguments.' >/dev/stderr
				exit 1
		end
	end
else
	find $prtdir -mindepth 2 -maxdepth 2 -type d | string replace "$prtdir/" '' | sort
end
