#!/bin/fish
#
# patch - Patch ports
# onodera, https://github.com/onodera-punpun

## EXECUTE

# Load util
source /usr/share/prt/util

getopts $argv | while read -l opt val
	switch $opt
		case h help
			echo -e 'Usage: prt patch [ports]\n'
			echo 'arguments:'
			echo '  -h,   --help            print help and exit'
			exit 0
		case '*'
			echo 'Invalid argument, use -h for a list of arguments.' >/dev/stderr
			exit 1
	end
end

prtonlyroot 'patch ports'

# Set patches
set patches (find /etc/prt/patch/ -type f -name '*.patch')

# Initialize count values
set total (count $repos)
set current 0

for patch in $patches
	set repo (echo $patch | rev | cut -d '/' -f 3 | rev)
	set port (echo $patch | rev | cut -d '/' -f 2 | rev)
	set file (echo $patch | rev | cut -d '/' -f 1 | rev | cut -d '.' -f 1)

	set current (math $current + 1)
	echo "Patching file $current/$total, $bright$repo/$port/$file$foreground."

	patch -N "$portdir/$repo/$port/$file" -i $patch >/dev/null
	if test $status -ge 1
		echo "Patching $bright$repo/$port/$file$foreground failed." >/dev/stderr
		exit 1
	end
end
