#!/bin/fish
#
# provide - Search ports for files
# onodera, https://github.com/onodera-punpun

## EXECUTE

# Load util
source /usr/share/prt/util

if test (count $argv) -ge 1
	getopts $argv | while read -l opt val
		switch $opt
			case h help
				echo -e 'Usage: prt provide [arguments] [queries]\n'
				echo 'arguments:'
				echo '  -h,   --help            print help and exit'
				exit 0
			case '*'
				set results (find $portdir -type f -name .footprint | xargs grep -i $val)

				for line in $results
					set port (echo $line | cut -d \t -f 1 | cut -d '.' -f 1 | string replace $portdir '' | string trim -c '/')

					if test $val != $port
						set val $port
						if test $status -ge 1
							exit 1
						end

						echo $val
					end

					if isatty stdout
						echo (echo $line | cut -d \t -f 3 | sed "s/^/$dark-> $foreground\//g")
					else
						echo (echo $line | cut -d \t -f 3 | sed "s/^/-> \//g")
					end
				end
		end
	end
else
	echo 'Please specify a query.' >/dev/stderr
	exit 1
end
