#!/bin/fish
#
# prtlib - Some common functions
# onodera, https://github.com/onodera-punpun

## FUNCTIONS

# This function checks if the uses has root access
function prtonlyroot
	if test (id -u) -ge 1
		echo "Only root can $argv." >/dev/stderr
		exit 1
	end
end

# This function reads the Pkgfile
function prtpkgfile
	if test -z $argv
		if test -f $pkgfile
			cat ./Pkgfile
		else
			echo 'Pkgfile not found.' >/dev/stderr
			exit 1
		end
	else
		if test -f $argv/Pkgfile
			cat $argv/Pkgfile
		else
			echo "Pkgfile $bright$argv$foreground not found." >/dev/stderr
			exit 1
		end
	end
end


## Execute

# Load config
source /etc/prtstuff/config

# Load colors
set foreground (set_color $foreground)
set bright (set_color $bright)
set dark (set_color $dark)
