#!/bin/fish
#
# sysup - Update outdated packages
# onodera, https://github.com/onodera-punpun

## EXECUTE

# Load util
source /usr/share/prt/util

# Initialize default option values
set verbose false

getopts $argv | while read -l opt val
	switch $opt
		case h help
			echo -e 'Usage: prt sysup [arguments]\n'
			echo 'arguments:'
			echo '  -s,   --script          toggle execution of pre- and post-install'
			echo '  -v,   --verbose         enable verbose output'
			echo '  -h,   --help            print help and exit'
			exit 0
		case s script
			if test $script = true
				set script false
			else
				set script true
			end
		case v verbose
			set verbose true
		case '*'
			echo 'Invalid argument, use -h for a list of arguments.' >/dev/stderr
			exit 1
	end
end

set method update
prtonlyroot "$method ports"
prtinstall (prt diff)
